import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "../dist/css/main.css";

export const metadata: Metadata = {
  title: "Remote Office - the best platform to upgrade your company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
